### ISSUE TITLE
Extra constructor required for Quorum transaction is not available after generation

### ISSUE THREAD

**Issue by hshar7** [web3j/web3j-quorum#14]
The contract code looks for a constructor that looks something like this:
`
    protected MyContract(String contractAddress,
                       Web3j web3j, TransactionManager transactionManager,
                       ContractGasProvider gasProvider) {
        super(BINARY, contractAddress, web3j, transactionManager, gasProvider);
    }`

But this constructor isn't getting generated using web3j cli tool. Is there something I am missing? I am using version 3.5.0 and web3j-Quorum 0.10.0

**Comment by iikirilov** [comment]
Please use web3j 3.6.0 command lines tools where this has been fixed. I will submit a PR to update web3j-quorum shortly

**Comment by iikirilov** [comment]
@jschiarizzi this issue is fixed and the PR is merged. 

 @snazha-blkio a new version needs to be released.

@hshar7 in the meantime you can add both web3j-quorum 0.10.0 and web3j 3.6.0 to your dependencies this should be resolved.

**Comment by jschiarizzi** [comment]
Thanks for the update.
