### ISSUE TITLE
Empty transaction logs in recieved in Transaction receipt on sending a transaction

### ISSUE THREAD

**Issue by TFPoC** [web3j/web3j-quorum#2]
Hi,

I am trying to use Topic filter in web3j (https://docs.web3j.io/filters.html#topic-filters-and-evm-events) with underlying Quorum blockchain running the 7nodes example.
I have used a simple contract (contract snippet as below), and converted it to a Java class using SolidityFunctionWrapperGenerator . On debugging the corresponding the call to multiply function from java code, I find that the transaction logs are empty (Transaction Receipt is as below).: 

Contract : 

pragma solidity ^0.4.0;
contract checkNotification { 
      
      event notify(uint input, uint result);
      
      function samplefunc(uint number) constant returns(uint result) {
        return number;
      }

      function multiply(uint a) returns(uint d) { 
               d = samplefunc(a);
               notify(a,d);
               
      }
}

**Transaction receipt:**

> eth.getTransactionReceipt("0x68d659ce0bfd200600cb0dd3fea1e3c05effd2b5450f1976f58a8e8fc69b7cc3")
{
  blockHash: "0x92c110b64a934865f4a03d5ac13d93ae9362557b4912e7edb0c9d3af647b635d",
  blockNumber: 1,
  contractAddress: "0x1932c48b2bf8102ba33b4a6b545c32236e342f34",
  cumulativeGasUsed: 0,
  from: "0xed9d02e382b34818e88b88a309c7fe71e65f419d",
  gasUsed: 0,
  logs: [],
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  root: "0x5e53860b87681053e430d219e8c9bfb196b0780e1538078670156f8847b15211",
  to: null,
  transactionHash: "0x68d659ce0bfd200600cb0dd3fea1e3c05effd2b5450f1976f58a8e8fc69b7cc3",
  transactionIndex: 0
}

As I understand, the value in the topics in logs[] will be required to set up my topic filter to capture the events taking place in the blockchain. Is this understanding correct? If not can you please correct me?

Can you let me know what might be causing the logs to be empty?

**Comment by conor10** [comment]
Was this a private transaction?

**Comment by cubo1123** [comment]
try to put a gasprice most high

**Comment by linerking** [comment]
hi,
I have the same problem, any one solved it?
