### ISSUE TITLE
No documentation on how to connect web3j to quorum 21.7.1 with multitenant nodes

### ISSUE THREAD

**Issue by subhasisbanik** [web3j/web3j-quorum#59]
I am trying to connect my quourm 21.7.1 network where the geth attach url has been modified to:

geth attach https://<IP>:22000?PSI=$PSI --rpcclitls.insecureskipverify --rpcclitoken "bearer $accessToken"

The current version in github does not provide any such document for :
1. How to pass the access token?
2. How to pass the Private State name in the URL

Please help

**Comment by subhasisbanik** [comment]
Hi @achraf17 , could you please help me here?

**Comment by subhasisbanik** [comment]
@MadelineMurray could you also help in this?

**Comment by subhasisbanik** [comment]
@achraf17 any update on this?

**Comment by subhasisbanik** [comment]
any update on this?

**Comment by antonydenyer** [comment]
You should be able to do something like:

```
    final HttpService httpService =
        new HttpService("http://localhost:22000?PSI=<$PSI>");
    httpService.addHeader("Authorization", "Bearer $accessToken");
```

Let us know how you get on.

**Comment by subhasisbanik** [comment]
Thanks for the reply @antonydenyer .
But it seems that the HttpService class or interface has been removed from this repo.
I tried using the codebase with:
<dependency>
  <groupId>org.web3j</groupId>
  <artifactId>quorum</artifactId>
  <version>4.8.4</version>
</dependency>

and had checked the examples in:
https://github.com/ConsenSys/quorum-examples/blob/master/examples/7nodes/samples/send-private-txn-java/src/main/java/com/quorum/web3j/example/SendRawPrivateTransaction.java

https://github.com/ConsenSys/quorum-examples/blob/master/examples/7nodes/samples/quorum-api-java/src/main/java/com/quorum/web3j/example/RaftRpcExample.java

Could you please help?

**Comment by antonydenyer** [comment]
I think you need to check your dependencies, web3j is a dependency of web3j-quorum


The full example of what you want for SendRawPrivateTransaction.java is something like:

```
X509TrustManager TRUST_ALL_CERTS = new X509TrustManager() {
    @Override
    public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) {
    }

    @Override
    public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) {
    }

    @Override
    public java.security.cert.X509Certificate[] getAcceptedIssuers() {
        return new java.security.cert.X509Certificate[] {};
    }
};

OkHttpClient.Builder newBuilder = new OkHttpClient.Builder();
SSLContext sslContext = SSLContext.getInstance("SSL");
sslContext.init(null, new TrustManager[] { TRUST_ALL_CERTS }, new java.security.SecureRandom());
newBuilder.sslSocketFactory(sslContext.getSocketFactory(), TRUST_ALL_CERTS);
newBuilder.hostnameVerifier((hostname, session) -> true);

HttpService service = new HttpService("https://localhost:22000?PSI=$PSI", newBuilder.build());
service.addHeader("Authorization", "bearer $accessToken");

quorum = Quorum.build(service);

```

but bear in mind this will be dependent on your auth and mps setup

**Comment by subhasisbanik** [comment]
@antonydenyer Thanks for letting me know.
Could you please provide me a sample code for executing a private transaction with PrivateState?
I have already set up a Quorum network with MPS and multitenancy enabled and am also able to geth attach to the same.

**Comment by antonydenyer** [comment]
Once you've initialised your `Quorum` instance the rest of the code remains the same.

**Comment by Purbaja** [comment]
@antonydenyer Thanks for the example. This worked for connecting via web3j with access token. 
Can you please help with sample snippet for generating access token through web3j for multitenant node.

**Comment by antonydenyer** [comment]
In the examples, you're basically doing a web request to hydra to fetch an access token. We're using hydra as an example identity provider. They have their own java client https://github.com/ory/hydra-client-java but you could easily use okhttp to make the request. It very much depends on your setup and use case.

**Comment by Purbaja** [comment]
Hi @antonydenyer , Have a query regarding the access token generation.
In a business application for multiple transactions can we use same access token? or we have to generate accesstoken each time we make a call to the quorum node to get/post a txn.

**Comment by antonydenyer** [comment]
It depends on what you have setup and when the token expires. You can use the same token multiple times if that's what you have configured. In the examples they have a 1 hour expiry time. 

https://oauth.net/2/bearer-tokens/
