### ISSUE TITLE
How to pass rpc token in web3j for a specific resident group in multitenant environment

### ISSUE THREAD

**Issue by Purbaja** [web3j/web3j-quorum#60]
Want to know how to pass rpc token in web3j for a specific resident group in multitenant environment, like we do while attaching geth -

 geth attach https://x.x.x.x:22000?PSI=PS1 --rpcclitls.insecureskipverify --rpcclitoken  XXX

Couldn't find any example or any function in the source code.

**Comment by Purbaja** [comment]
Hi
@MadelineMurray  , can u please suggest something for this issue?

**Comment by antonydenyer** [comment]
Duplicate issue https://github.com/web3j/web3j-quorum/issues/59
