### ISSUE TITLE
4.9.0+ release

### ISSUE THREAD

**Issue by diega** [web3j/web3j-quorum#66]
## Feature description
Given that web3j 4.9.0 has changed it's dependencies, using `org.web3j:quorum:4.8.4` along with `org.web3j:core:4.9.0` results in a really cluttered classpath.

**Comment by antonydenyer** [comment]
@AlexandrouR any chance you could do a release for us?

**Comment by AlexandrouR** [comment]
will do one today.

**Comment by AlexandrouR** [comment]
release is out closing this
